name: Build

on:
  push:
    branches:
    - master-ceu

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[build skip]')"
    name: "Pre Release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short $GITHUB_SHA)"
    - name: Export Client Curse Pack
      shell: bash
      run: |
        chmod +x ./packwiz
        ./packwiz curseforge export -o client.zip
        ./packwiz list > modlist.txt
        mkdir -p ./buildOut/
        mv ./modlist.txt ./buildOut/
        mv ./client.zip ./buildOut/
    - name: Bootstrap
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
    - name: Install requests
      run: |
        pip install requests
    - run: python build/download.py
    - name: Download
      shell: bash
      run: |
        serverPack="server.zip"
        cp LICENSE build/server/
          
        cd build/server
        java -jar packwiz-installer-bootstrap.jar ../../pack.toml
          
        zip -r $serverPack config
        zip -r $serverPack groovy
        zip -r $serverPack libraries
        zip -r $serverPack mods
        zip -r $serverPack structures
          
        zip -m $serverPack launch.sh
        zip -m $serverPack forge-1.12.2-14.23.5.2860.jar
        zip -m $serverPack LICENSE
        zip -m $serverPack minecraft_server.1.12.2.jar
          
        cd ..
          
        mv $serverPack buildOut/$serverPack
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: ${{ steps.vars.outputs.sha_short }}
          files: |
            buildOut/client.zip
            buildOut/server.zip
            buildOut/modlist.txt

