name: Build

on:
  push:
    branches:
    - master-ceu

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[build skip]')"
    name: "Pre Release"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
          echo "::set-output name=sha_short::$(git rev-parse --short $GITHUB_SHA)"
    - name: Install requests
      run: |
          pip install requests
    
    # Export client curse pack & Start serve on localhost:8080
    - name: Export Client Curse Pack
      shell: bash
      run: |
        chmod +x ./packwiz
        ./packwiz curseforge export -o buildOut/client.zip
        ./packwiz serve

    # Run bootstrap to download server files
    - name: Bootstrap
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
    - run: python server/download.py
    - name: Download
      shell: bash
      run: |
        serverPack="server.zip"

        cd server
        java -jar packwiz-installer-bootstrap.jar -g -s server http://localhost:8080/pack.toml

        zip -r $serverPack config
        zip -r $serverPack groovy
        zip -r $serverPack mods
        zip -r $serverPack structures
        zip -m $serverPack launch.sh

        cd ..

        mv ./server/$serverPack buildOut/$serverPack

    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: ${{ steps.vars.outputs.sha_short }}
        files: |
          buildOut/client.zip
          buildOut/server.zip
          buildOut/modlist.html
        