name: Update Toml

on:
  workflow_dispatch

jobs:
  build:
    name: "Update Toml"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: refresh
      shell: bash
      run: |
        chmod +x ./packwiz
        ./packwiz refresh
    - name: Commit and push gradle.properties
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "update tomol"
        commit_options: "--no-verify"
        file_pattern: pack.toml index.toml